### ISSUE TITLE
Sorting Floats - Does this work?

### ISSUE THREAD

**Issue by arcman7** [kishimisu/WebGPU-Radix-Sort#1]
https://github.com/kishimisu/WebGPU-Radix-Sort/blob/32ce7b262d55c9e4f8837ee66f5fac6c941a48a7/example/tests.js#L39

**Comment by kishimisu** [comment]
Yes, but for now this only only works if all elements in the array are unsigned (>= 0)

**Comment by arcman7** [comment]
That's fine; with a little effort on my part that still works for me... very cool project! Thanks!
